# Generated by Django 6.0.1 on 2026-02-03 06:43

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('label', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('judul', models.CharField(max_length=200)),
                ('deskripsi', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('TODO', 'Todo'), ('SELESAI', 'Selesai'), ('DIARSIPKAN', 'Diarsipkan')], default='TODO', max_length=20)),
                ('prioritas', models.CharField(choices=[('RENDAH', 'Rendah'), ('SEDANG', 'Sedang'), ('TINGGI', 'Tinggi')], default='SEDANG', max_length=20)),
                ('tanggal_jatuh_tempo', models.DateField(blank=True, null=True)),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('diubah_pada', models.DateTimeField(auto_now=True)),
                ('labels', models.ManyToManyField(blank=True, related_name='todos', to='label.label')),
            ],
        ),
    ]
