# Generated by Django 6.0.1 on 2026-02-05 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('label', '0002_remove_label_diubah_pada_remove_label_warna_and_more'),
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='label',
            field=models.ManyToManyField(blank=True, to='label.label'),
        ),
    ]
