# Generated by Django 6.0.1 on 2026-02-05 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('label', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='label',
            name='diubah_pada',
        ),
        migrations.RemoveField(
            model_name='label',
            name='warna',
        ),
        migrations.AlterModelTable(
            name='label',
            table='label',
        ),
    ]
